prometheus:
  prometheusSpec:
    retention: 7d
    retentionSize: 1600MB
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        memory: 512Mi

    storageSpec:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-gp3-retain
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 2Gi

  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - home.prometheus
    paths:
      - /
    pathType: Prefix

grafana:
  deploymentStrategy:
    type: Recreate
  persistence:
    enabled: true
    storageClassName: ebs-gp3-retain
    size: 500Mi

  ingress:
    enabled: true
    ingressClassName: cilium
    hosts:
      - home.grafana
    path: /
    pathType: Prefix

alertmanager:
  ingress:
    enabled: false
    ingressClassName:
    hosts:
    paths:
    pathType:

  alertmanagerSpec:
    storage:
      volumeClaimTemplate:
        spec:
          storageClassName: ebs-gp3-retain
          accessModes: ["ReadWriteOnce"]
          resources:
            requests:
              storage: 256Mi
  config:
    route:
      receiver: 'discord'
      group_by: ['alertname', 'namespace']
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h

kubeProxy:
  enabled: false


