apiVersion: v1
kind: Secret
metadata:
    name: kps-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:9b3i2MeiS/sEjnj0mPF11ItDlklhF7wL4eVKJcVfrmWldXW1SH+s/4+M/1LxWkTlBMwqZ7cCdAfaBlB44uJQwyTCjJbSz20d4dOtuXHV7dKB7tkRj4b5xJMIH+p6t0QW1ONs2HLM/guX07wkX2lMHFqkCXDtr6ewwZbWOwhJ4myg9gOo7F5abxtZEVKPh5UCKPITq03pSPhwRA7LVgVz743R82bM/WyMklf4CgV9Mg09z6OVlYX5BgnjFY2Eb2NcIh994w3/pM6o5Vn9d8c0cwWdVXPls99jxnXlnRna79I9xTrwtO9ehhpFZcKHYL0RA9YJ0Unf44zE5GZu/jYRmd+dPdgQDAX9/0jlsJk=,iv:vcLhWAP6m+/ijk7/si8zijfhDZ3I0e38tE58cy3xen8=,tag:oPryavHvbSkQsxBBLUkboQ==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYk1kZzQ5LzJHTUd0VDg3
            YllDYnNibEx1Ny9wclNhdUJUQWF5LzYzQXpRCmR1N1NmbmVZQlZ3aFBPcG5YUmVV
            Sk9ETWxRdkhxRithYmFyc1pjOGZDL1UKLS0tICs2Z2hQZkpyKytNdGRCMUtxVWI3
            OVUrWTJlZlJ1SzlPUDRZUGlyNXRxazQKAERMtJVt3LxQFOakMcl2ASOGxNru5Ju2
            tl1b5xafUmbYJ6FJ3yCprkWfH6cOTcip8RAl4UP3bcc+KIBXJVvrAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vrt77vkusj3eg0440j99gjk6qcj9pqgz4hf8thrrnzqgwztv3umq8at23u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T16:56:35Z"
    mac: ENC[AES256_GCM,data:bIVQBRjPFrgvuVOjb8nFBEb+ZEavpq/XZ46RhoXzXt60rH0pYJql/F+WflXqTbLSZkKpz+CoToZjwbCAKNTHhK2WgH8s83GgHIuznIdQ8DhOTeRLjYJKwAnrBAcS8g43o4pL3k10IFTpwZFso5YuDulwRpJ2lIzIRfyVuC7Tw1c=,iv:hfProDhNSEiV9WfU2r2O3iZVPPwzDQopBlk9UmICdjc=,tag:WElZ8DoNgL4p7X6utgxF9A==,type:str]
    version: 3.13.3
