apiVersion: v1
kind: Secret
metadata:
    name: kps-secrets
    namespace: monitoring
type: Opaque
stringData:
    values.yaml: ENC[AES256_GCM,data:wfPRANtDSjOOoqGx2XPCG3uhby3RcHLBChob3bM8ORMBW6FkwrTvUe4J17pCmaVnPPsbAo7oVksISykUpqIkhocnas5gUQa5GVr5ynQUD/4rj3dt6wB0Uz16I0c7EBEWV14wwgC0s2y8p9ah3SE8L66AT6kUHAqTsv1VcDR/MxRolazfMj/Wuaazt0cp6IwFr1NNlecD36RSOz+JZs+UhNOhGWhzGb2HxHxdVmoaKmA4gPLP7SgmW0fdZhNPyUGPylI4rGb/ORlhq0ubePfgXTCDIR0rPBwJ3EAsORJMBNXagn/V8utnog83S97t4rcgx0o04vevdfycB5cm3e4Ve8mf1E5BllGBmEQswS+xg8u6Jnf7eWf4c0/E1KkxVBJ3X4c=,iv:nk3kLYxNeBvA+c4jvicBapiPBk4lBrMDXr/qGzVDMkM=,tag:xtMkDohSa5O7ZoE9HLGlYA==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBvYk1kZzQ5LzJHTUd0VDg3
            YllDYnNibEx1Ny9wclNhdUJUQWF5LzYzQXpRCmR1N1NmbmVZQlZ3aFBPcG5YUmVV
            Sk9ETWxRdkhxRithYmFyc1pjOGZDL1UKLS0tICs2Z2hQZkpyKytNdGRCMUtxVWI3
            OVUrWTJlZlJ1SzlPUDRZUGlyNXRxazQKAERMtJVt3LxQFOakMcl2ASOGxNru5Ju2
            tl1b5xafUmbYJ6FJ3yCprkWfH6cOTcip8RAl4UP3bcc+KIBXJVvrAw==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vrt77vkusj3eg0440j99gjk6qcj9pqgz4hf8thrrnzqgwztv3umq8at23u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-08-01T20:12:12Z"
    mac: ENC[AES256_GCM,data:rWVlm4kowkpADRgWc75e1qnku2EtNc2BiJxUQCp8jBHyXRVR5NbQIhSh82ILwsPav3CUVH3NeDt0B5EmrgySxY97Uoy7YrTar1T/Wu0DHUG/Kr6NbkbDMbFd2OxfUznDfYd4cyXzS9TbjNoP4CZRWXzgK6p1igAF4+pcKBiorhw=,iv:Oq1d5rcvQGlDH9lsgZXUrd5C2hPnaqyBHAg++KzUxJk=,tag:YB628/rhltpmtoG+lRKOaw==,type:str]
    version: 3.13.3
