[control_planes]
cp1 ansible_host=51.20.96.162 private_ip=10.42.1.74
[workers]
worker1 ansible_host=13.63.167.143 private_ip=10.42.1.137
worker2 ansible_host=13.48.106.90 private_ip=10.42.1.155

[nodes:children]
control_planes
workers

[all:vars]
ansible_user=ubuntu
ansible_python_interpreter=/usr/bin/python3.12
ansible_ssh_common_args='-o StrictHostKeyChecking=accept-new'

