[control_planes]
cp1 ansible_host=13.51.233.105 private_ip=10.42.1.172

[workers]
worker1 ansible_host=13.62.20.205 private_ip=10.42.1.133
worker2 ansible_host=13.63.161.47 private_ip=10.42.1.231

[nodes:children]
control_planes
workers

