apiVersion: v1
kind: Namespace
metadata:
    name: freshrss
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHY5bTAveU9pSWU3alo4
            aHVOOTBFc1VRdjVBQjlYaDVrNjlaU3Mvc0hZCll6UStKZmtJSi8xMk1GcWpCUEpM
            V1JrdllnbDdibzIxaWRYZmN0V0tsTlEKLS0tIDcwYTdTcStHUFpjYmhPUmN4RnBi
            RUk2QVJkZ1B5UXJacGlhSUljMjkzUmMKXgK9AMpYj7bJqPhcq+AdpTKdVQuNd2tO
            3yUgY/6v4AKAx/L/b6Ua6Ko3t/g6lAAPxQMNF3byhtR6gZ7JAJE86g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vrt77vkusj3eg0440j99gjk6qcj9pqgz4hf8thrrnzqgwztv3umq8at23u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T16:21:39Z"
    mac: ENC[AES256_GCM,data:qj9yjxTOmUxclcofReJuwE+2y0Qxi/JltKPyzxuWPczNSf+3MszCfmenLC8GUFAasM1WlRPs8dx2a+Oh0i2vrv0X0j4/h+MdS3/SXVTPC8ykd8XvqPxe/9MynyHJjMgtX5kQeZhfUQL1esHlyCBddoPeVGvLx6rSBLFQ3v4hIsI=,iv:1tWxqLFVadRPkUvoVbCFz9TZAsEghNFHKxRSStOP5g8=,tag:0cRysUcXRjnroeEld6HsGg==,type:str]
    version: 3.13.3
---
# secret.yaml (LOCAL ONLY - DO NOT COMMIT)
apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: freshrss
type: Opaque
stringData:
    #ENC[AES256_GCM,data:P492SgY7dbzjoIuG6S62RZsrgX7GNMJY3UM5DzlRTl9UXpTkqRGODza7U0BR1sWBuMLYMvUto/Tw2TKpp0sXags=,iv:lFGea/HCSIkr+kqyLzEc346NTIthH8iYcnDPEs9Q2Xc=,tag:/IdiledTbnfjrQFpNPUvJw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lLBrRDrBLgmw,iv:7yLMM9+SrTNxcHXFxRQb7yEy9PL/4rkZpaWSHLHUeWc=,tag:ckgFjFriuQi51YFS4cFhMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHY5bTAveU9pSWU3alo4
            aHVOOTBFc1VRdjVBQjlYaDVrNjlaU3Mvc0hZCll6UStKZmtJSi8xMk1GcWpCUEpM
            V1JrdllnbDdibzIxaWRYZmN0V0tsTlEKLS0tIDcwYTdTcStHUFpjYmhPUmN4RnBi
            RUk2QVJkZ1B5UXJacGlhSUljMjkzUmMKXgK9AMpYj7bJqPhcq+AdpTKdVQuNd2tO
            3yUgY/6v4AKAx/L/b6Ua6Ko3t/g6lAAPxQMNF3byhtR6gZ7JAJE86g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vrt77vkusj3eg0440j99gjk6qcj9pqgz4hf8thrrnzqgwztv3umq8at23u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T16:21:39Z"
    mac: ENC[AES256_GCM,data:qj9yjxTOmUxclcofReJuwE+2y0Qxi/JltKPyzxuWPczNSf+3MszCfmenLC8GUFAasM1WlRPs8dx2a+Oh0i2vrv0X0j4/h+MdS3/SXVTPC8ykd8XvqPxe/9MynyHJjMgtX5kQeZhfUQL1esHlyCBddoPeVGvLx6rSBLFQ3v4hIsI=,iv:1tWxqLFVadRPkUvoVbCFz9TZAsEghNFHKxRSStOP5g8=,tag:0cRysUcXRjnroeEld6HsGg==,type:str]
    version: 3.13.3
