apiVersion: v1
kind: Secret
metadata:
    name: db-secret
    namespace: freshrss
type: Opaque
stringData:
    #ENC[AES256_GCM,data:P492SgY7dbzjoIuG6S62RZsrgX7GNMJY3UM5DzlRTl9UXpTkqRGODza7U0BR1sWBuMLYMvUto/Tw2TKpp0sXags=,iv:lFGea/HCSIkr+kqyLzEc346NTIthH8iYcnDPEs9Q2Xc=,tag:/IdiledTbnfjrQFpNPUvJw==,type:comment]
    POSTGRES_PASSWORD: ENC[AES256_GCM,data:lLBrRDrBLgmw,iv:7yLMM9+SrTNxcHXFxRQb7yEy9PL/4rkZpaWSHLHUeWc=,tag:ckgFjFriuQi51YFS4cFhMw==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhWHY5bTAveU9pSWU3alo4
            aHVOOTBFc1VRdjVBQjlYaDVrNjlaU3Mvc0hZCll6UStKZmtJSi8xMk1GcWpCUEpM
            V1JrdllnbDdibzIxaWRYZmN0V0tsTlEKLS0tIDcwYTdTcStHUFpjYmhPUmN4RnBi
            RUk2QVJkZ1B5UXJacGlhSUljMjkzUmMKXgK9AMpYj7bJqPhcq+AdpTKdVQuNd2tO
            3yUgY/6v4AKAx/L/b6Ua6Ko3t/g6lAAPxQMNF3byhtR6gZ7JAJE86g==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1vrt77vkusj3eg0440j99gjk6qcj9pqgz4hf8thrrnzqgwztv3umq8at23u
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-31T16:35:54Z"
    mac: ENC[AES256_GCM,data:xiZPaiL8lk+EiT//b9s9rImbH9hSUd8tCxy3Q8Gtueb6dhBqmzbPvruP6anPMQfycJ2QskMQFbL1A4GgOqxzNQ+yOoMETtQ14IVwjepkrXGMp1rFQqaNv2r/vfyYCnz0ykaZQm/pFTcApimtavV7fRezhtLAUMaQpkiHx8AP/gI=,iv:cQIJnQlFy2EqEYm6GvQDn0G3XZyVM6f0SLuOwFdDreM=,tag:3Lml9Mj9Xf112yBtmJV5lA==,type:str]
    version: 3.13.3
