apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: freshrss-postgres
  namespace: freshrss
spec:
  podSelector:
    matchLabels:
      app.kubernetes.io/name: postgres
  policyTypes:
    - Ingress
  ingress:
    - from:
      - podSelector:
          matchLabels:
            app: freshrss
      - podSelector:
          matchLabels:
            app.kubernetes.io/instance: pgexporter
      ports:
      - protocol: TCP
        port: 5432


